# Site settings
name: Melissa J. Barca
email: melissajbranagan@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, C++, SQL, DB2, Software Design, Relational Databases, Agile, Pair Programming"
skills: "Senior Software Engineer in San Diego, CA"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/melissa-oldham-barca-01891680
  - title: instagram
    url: https://instagram.com/melissajene
#  - title: github
#    url: https://github.com/mbranagan
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  transparent: FFEEAD
  primary: FF6F69
  primary-rgb: "255, 111, 105"
  secondary: 96CEB4
  secondary-dark: 88D8B0
  section-tout: FFEEAD



# Build settings
markdown: kramdown
permalink: pretty
